#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include "stdio_compat.h"
#include <malloc.h>
#include <dmaKit.h>
#include <gsKit.h>
#include <gsToolkit.h>
#include <libpad.h>
#include <libmc.h>
#include <libkbd.h>
#include <timer.h>
#include <unistd.h>
#include <sbv_patches.h>

#include "runner.h"
#include "runner_keyboard.h"
#include "vm.h"
#include "../data_win.h"
#include "../json_reader.h"
#include "ps2_file_system.h"
#ifdef USE_PS2_AUDIO
#include "ps2_audio_system.h"
#endif
#include "gs_renderer.h"
#include "noop_audio_system.h"
#include "ps2_utils.h"
#include "ps2_gamepad.h"
#include "stb_ds.h"
#include "utils.h"
#include "../profiler.h"
#include "ps2/ps2_overlay.h"
#include "gettime.h"

#ifdef GPROF_PROFILING
#include <ps2prof.h>
#endif

// Embedded ps2sdk IRX modules (generated by bin2c at build time)
extern unsigned char freesio2_irx[];
extern unsigned int size_freesio2_irx;
extern unsigned char mcman_irx[];
extern unsigned int size_mcman_irx;
extern unsigned char mcserv_irx[];
extern unsigned int size_mcserv_irx;
extern unsigned char freepad_irx[];
extern unsigned int size_freepad_irx;
extern unsigned char usbd_irx[];
extern unsigned int size_usbd_irx;
extern unsigned char ps2kbd_irx[];
extern unsigned int size_ps2kbd_irx;
#ifdef USE_PS2_AUDIO
extern unsigned char freesd_irx[];
extern unsigned int size_freesd_irx;
extern unsigned char audsrv_irx[];
extern unsigned int size_audsrv_irx;
#endif

// Total main RAM in bytes.
static int MAX_MEMORY_BYTES = 0;

// Heap ceiling: Captured once at startup (before any game allocations) and used as a stable denominator in the debug overlay.
static int heapCeilingBytes = 0;

// 256-byte aligned buffers for libpad (one per port)
static char padBuf[2][256] BS_ALIGN(64);

// Controller button to GML key mapping
typedef struct {
    uint16_t padButton;
    int32_t gmlKey;
} PadMapping;

static PadMapping* pad1Mappings = nullptr;
static int pad1MappingCount = 0;
static PadMapping* pad2Mappings = nullptr;
static int pad2MappingCount = 0;

// Previous frame's button state per pad (active-low; 0xFFFF = all released)
static uint16_t prevButtons[2] = {0xFFFF, 0xFFFF};

// Whether each port was successfully opened (padPortOpen succeeded)
static bool padOpened[2] = {false, false};

// Whether each pad was STABLE last frame (for disconnect/reconnect edge detection)
static bool padWasStable[2] = {false, false};

// Whether the controllers should be exposed via the GameMaker gamepad API
static bool gamepadApiEnabled = false;

static void parsePadMappings(JsonValue* configRoot, const char* key, PadMapping** outMappings, int* outCount, const char* logLabel) {
    JsonValue* mappingsObj = JsonReader_getJsonValueByKey(configRoot, key);
    if (mappingsObj == nullptr || !JsonReader_isObject(mappingsObj)) return;
    int count = JsonReader_objectLength(mappingsObj);
    PadMapping* mappings = (PadMapping *)safeMalloc(sizeof(PadMapping) * count);
    repeat(count, i) {
        const char* padButtonStr = JsonReader_getJsonKeyByIndex(mappingsObj, i);
        JsonValue* gmlKeyVal = JsonReader_getJsonValueByIndex(mappingsObj, i);
        mappings[i].padButton = (uint16_t) atoi(padButtonStr);
        mappings[i].gmlKey = (int32_t) JsonReader_getInt(gmlKeyVal);
        printf("CONFIG.JSN: %s mapping pad=%d -> gmlKey=%d\n", logLabel, mappings[i].padButton, mappings[i].gmlKey);
    }
    *outMappings = mappings;
    *outCount = count;
}

static void pollPad(Runner* runner, int port, PadMapping* mappings, int mappingCount, uint16_t* prev, bool* wasStable) {
    int state = padGetState(port, 0);
    bool stable = (state == PAD_STATE_STABLE);

    if (!stable) {
        if (*wasStable) {
            // Disconnect edge: release every key whose button was held.
            repeat(mappingCount, i) {
                uint16_t mask = mappings[i].padButton;
                if ((*prev & mask) == 0) {
                    RunnerKeyboard_onKeyUp(runner->keyboard, mappings[i].gmlKey);
                }
            }
            *prev = 0xFFFF;
            *wasStable = false;
        }
        return;
    }

    if (!*wasStable) {
        // Reconnect edge: avoid phantom presses from buttons that were held when the pad came back.
        *prev = 0xFFFF;
        *wasStable = true;
    }

    struct padButtonStatus padStatus;
    unsigned char padResult = padRead(port, 0, &padStatus);
    if (padResult == 0) return;

    uint16_t buttons = padStatus.btns;
    repeat(mappingCount, i) {
        uint16_t mask = mappings[i].padButton;
        int32_t gmlKey = mappings[i].gmlKey;

        // PS2 buttons are active-low: 0 = pressed, 1 = released
        bool wasPressed = (*prev & mask) == 0;
        bool isPressed = (buttons & mask) == 0;

        if (isPressed && !wasPressed) {
            RunnerKeyboard_onKeyDown(runner->keyboard, gmlKey);
        } else if (!isPressed && wasPressed) {
            RunnerKeyboard_onKeyUp(runner->keyboard, gmlKey);
        }
    }
    *prev = buttons;
}

// ===[ USB Keyboard ]===

static bool kbdAvailable = false;

// Shift modifier state (left-or-right).
static bool kbdShiftHeld = false;

// Map a USB HID usage code (as delivered by ps2kbd.irx in RAW mode) to a GML VK code.
static int32_t hidUsageToGmlKey(uint8_t hid) {
    // Letters: HID 0x04..0x1D -> ASCII 'A'..'Z' (GML uses uppercase ASCII)
    if (hid >= 0x04 && hid <= 0x1D) return (int32_t) ('A' + (hid - 0x04));
    // Numbers: HID 0x1E..0x26 -> '1'..'9', 0x27 -> '0'
    if (hid >= 0x1E && hid <= 0x26) return (int32_t) ('1' + (hid - 0x1E));
    if (hid == 0x27) return (int32_t) '0';
    // Special keys need mapping
    switch (hid) {
        case 0x28: return VK_ENTER;      // Enter
        case 0x29: return VK_ESCAPE;     // Escape
        case 0x2A: return VK_BACKSPACE;  // Backspace
        case 0x2B: return VK_TAB;        // Tab
        case 0x2C: return VK_SPACE;      // Space
        case 0x3A: return VK_F1;
        case 0x3B: return VK_F2;
        case 0x3C: return VK_F3;
        case 0x3D: return VK_F4;
        case 0x3E: return VK_F5;
        case 0x3F: return VK_F6;
        case 0x40: return VK_F7;
        case 0x41: return VK_F8;
        case 0x42: return VK_F9;
        case 0x43: return VK_F10;
        case 0x44: return VK_F11;
        case 0x45: return VK_F12;
        case 0x49: return VK_INSERT;
        case 0x4A: return VK_HOME;
        case 0x4B: return VK_PAGEUP;
        case 0x4C: return VK_DELETE;
        case 0x4D: return VK_END;
        case 0x4E: return VK_PAGEDOWN;
        case 0x4F: return VK_RIGHT;
        case 0x50: return VK_LEFT;
        case 0x51: return VK_DOWN;
        case 0x52: return VK_UP;
        case 0xE0: case 0xE4: return VK_CONTROL;  // Left/Right Ctrl
        case 0xE1: case 0xE5: return VK_SHIFT;    // Left/Right Shift
        case 0xE2: case 0xE6: return VK_ALT;      // Left/Right Alt
        default: return -1;
    }
}

// Translate a HID usage code to an ASCII character for RunnerKeyboard_onCharacter.
// Also handles when the shift key is held.
static unsigned int hidUsageToAsciiChar(uint8_t hid, bool shift) {
    // Letters A-Z: HID 0x04..0x1D
    if (hid >= 0x04 && hid <= 0x1D) {
        char base = (char) ('a' + (hid - 0x04));
        return (unsigned int) (shift ? (base - 32) : base);
    }

    // Digits / top-row symbols: 0x1E..0x26 -> 1..9, 0x27 -> 0
    static const char digitsUnshifted[10] = {'1','2','3','4','5','6','7','8','9','0'};
    static const char digitsShifted[10]   = {'!','@','#','$','%','^','&','*','(',')'};
    if (hid >= 0x1E && hid <= 0x26) return (unsigned int) (shift ? digitsShifted[hid - 0x1E] : digitsUnshifted[hid - 0x1E]);
    if (hid == 0x27) return (unsigned int) (shift ? digitsShifted[9] : digitsUnshifted[9]);

    switch (hid) {
        case 0x28: return (unsigned int) '\r';  // Enter
        case 0x2A: return (unsigned int) '\b';  // Backspace
        case 0x2B: return (unsigned int) '\t';  // Tab
        case 0x2C: return (unsigned int) ' ';   // Space
        case 0x2D: return (unsigned int) (shift ? '_' : '-');
        case 0x2E: return (unsigned int) (shift ? '+' : '=');
        case 0x2F: return (unsigned int) (shift ? '{' : '[');
        case 0x30: return (unsigned int) (shift ? '}' : ']');
        case 0x31: return (unsigned int) (shift ? '|' : '\\');
        case 0x33: return (unsigned int) (shift ? ':' : ';');
        case 0x34: return (unsigned int) (shift ? '"' : '\'');
        case 0x35: return (unsigned int) (shift ? '~' : '`');
        case 0x36: return (unsigned int) (shift ? '<' : ',');
        case 0x37: return (unsigned int) (shift ? '>' : '.');
        case 0x38: return (unsigned int) (shift ? '?' : '/');
        default: return 0;
    }
}


int main(int argc, char* argv[]) {
    (void)argc;
    SifInitRpc(0);
    sbv_patch_enable_lmb();

    // Ask the kernel how much main RAM we actually have.
    MAX_MEMORY_BYTES = (int) GetMemorySize();

    // Snapshot the heap ceiling BEFORE anything else allocates. sbrk(0) at this point is the heap frontier after newlib's baseline reservations; mallinfo.uordblks is what newlib has already handed out to startup code. Their sum (added to the sbrk runway) is the total bytes user code could ever cumulatively hold live.
    {
        struct mallinfo mi = mallinfo();
        heapCeilingBytes = (MAX_MEMORY_BYTES - (int) (uintptr_t) sbrk(0)) + mi.uordblks;
    }

    PS2Utils_extractDeviceKey(argv[0]);

    fprintf(stderr, "argv0 is %s, device key is %s\n", argv[0], deviceKey.key);

    PS2Utils_loadFSDrivers();

    fprintf(stderr, "Loaded FS drivers!\n");

    char* dataWinPath = PS2Utils_createDevicePath("DATA.WIN");

    printf("Butterscotch PS2 - Loading %s\n", dataWinPath);

    // ===[ Initialize gsKit ]===
    // This must happen first so we can show the loading screen during other init steps
    GSGLOBAL* gsGlobal = gsKit_init_global();
    gsGlobal->Mode = GS_MODE_NTSC;
    gsGlobal->Interlace = GS_INTERLACED;
    gsGlobal->Field = GS_FIELD;
    gsGlobal->Width = 640;
    gsGlobal->Height = 448;
    gsGlobal->PSM = GS_PSM_CT16;
    gsGlobal->PSMZ = GS_PSMZ_16;
    gsGlobal->DoubleBuffering = GS_SETTING_ON;
    gsGlobal->ZBuffering = GS_SETTING_OFF;

    gsGlobal->PrimAAEnable = GS_SETTING_OFF;

    dmaKit_init(D_CTRL_RELE_OFF, D_CTRL_MFD_OFF, D_CTRL_STS_UNSPEC, D_CTRL_STD_OFF, D_CTRL_RCYC_8, 1 << DMA_CHANNEL_GIF);
    dmaKit_chan_init(DMA_CHANNEL_GIF);

    gsKit_init_screen(gsGlobal);
    // Use ONE SHOT mode
    gsKit_mode_switch(gsGlobal, GS_ONESHOT);

    // ===[ Initialize debug overlay ]===
    PS2Overlay_init(gsGlobal, MAX_MEMORY_BYTES, heapCeilingBytes);

    // ===[ Initialize Controller ]===
    PS2Overlay_drawStatusScreen(nullptr, "Initializing controller...", false);

    int ret;
    ret = SifExecModuleBuffer(freesio2_irx, size_freesio2_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load freesio2: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(mcman_irx, size_mcman_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load mcman: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(mcserv_irx, size_mcserv_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load mcserv: %d\n", ret);
        return 1;
    }
    ret = mcInit(MC_TYPE_MC);
    if (0 > ret) {
        printf("Failed to init libmc: %d\n", ret);
        return 1;
    }
    ret = SifExecModuleBuffer(freepad_irx, size_freepad_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load freepad: %d\n", ret);
        return 1;
    }

    padInit(0);
    padOpened[0] = (padPortOpen(0, 0, padBuf[0]) != 0);
    padOpened[1] = (padPortOpen(1, 0, padBuf[1]) != 0);
    if (!padOpened[0]) printf("Warning: failed to open pad port 0\n");
    if (!padOpened[1]) printf("Warning: failed to open pad port 1\n");

    // ===[ Load USB Keyboard IOP Modules ]===
    int usbdRet = SifExecModuleBuffer(usbd_irx, size_usbd_irx, 0, nullptr, nullptr);
    if (0 > usbdRet) {
        printf("Warning: failed to load usbd: %d (keyboard disabled)\n", usbdRet);
    } else {
        int kbdRet = SifExecModuleBuffer(ps2kbd_irx, size_ps2kbd_irx, 0, nullptr, nullptr);
        if (0 > kbdRet) {
            printf("Warning: failed to load ps2kbd: %d (keyboard disabled)\n", kbdRet);
        } else if (PS2KbdInit() == 0) {
            printf("Warning: PS2KbdInit failed (keyboard disabled)\n");
        } else {
            PS2KbdSetReadmode(PS2KBD_READMODE_RAW);
            PS2KbdSetBlockingMode(PS2KBD_NONBLOCKING);
            kbdAvailable = true;
            printf("USB keyboard initialized\n");
        }
    }

#ifdef USE_PS2_AUDIO
    // ===[ Load Audio IOP Modules ]===
    ret = SifExecModuleBuffer(freesd_irx, size_freesd_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load freesd: %d\n", ret);
    }
    ret = SifExecModuleBuffer(audsrv_irx, size_audsrv_irx, 0, nullptr, nullptr);
    if (0 > ret) {
        printf("Failed to load audsrv: %d\n", ret);
    }
#endif

    // Wait for pad to be ready
    PS2Overlay_drawStatusScreen(nullptr, "Waiting for controller...", false);
    int padState;
    do {
        padState = padGetState(0, 0);
    } while (PAD_STATE_STABLE != padState && PAD_STATE_FINDCTP1 != padState);

    printf("Controller initialized\n");

    // ===[ Load CONFIG.JSN ]===
    PS2Overlay_drawStatusScreen(nullptr, "Loading CONFIG.JSN...", false);

    char* configJsonPath = PS2Utils_createDevicePath("CONFIG.JSN");
    FILE* configFile = fopen(configJsonPath, "rb");
    JsonValue* configRoot = nullptr;

    if (configFile != nullptr) {
        fseek(configFile, 0, SEEK_END);
        long configSize = ftell(configFile);
        fseek(configFile, 0, SEEK_SET);

        char* configJsonText = (char *)safeMalloc((size_t) configSize + 1);
        size_t configBytesRead = fread(configJsonText, 1, (size_t) configSize, configFile);
        configJsonText[configBytesRead] = '\0';
        fclose(configFile);

        configRoot = JsonReader_parse(configJsonText);
        free(configJsonText);
    }
    free(configJsonPath);

    if (configRoot == nullptr) {
        PS2Overlay_drawStatusScreen(nullptr, "CONFIG.JSN invalid or not found!", false);
        while (true) {}
    }

    bool lazyLoadRooms = JsonReader_getBool(JsonReader_getJsonValueByKey(configRoot, "lazyLoadRooms"));
    StringBooleanEntry* eagerRooms = nullptr; // stb_ds string-keyed set; keys borrowed from configRoot
    JsonValue* eagerArr = JsonReader_getJsonValueByKey(configRoot, "eagerlyLoadedRooms");
    int n = JsonReader_arrayLength(eagerArr);
    repeat(n, i) {
        const char* name = JsonReader_getString(JsonReader_getArrayElement(eagerArr, i));
        if (name != nullptr) shput(eagerRooms, (char*) name, true);
    }

    // ===[ Parse data.win ]===
    PS2Overlay_drawStatusScreen(nullptr, "Loading data.win...", false);

    DataWinParserOptions options = {0};
    options.parseGen8 = true;
    options.parseOptn = true;
    options.parseLang = true;
    options.parseExtn = true;
    options.parseSond = true;
    options.parseAgrp = true;
    options.parseSprt = true;
    options.parseBgnd = true;
    options.parsePath = true;
    options.parseScpt = true;
    options.parseGlob = true;
    options.parseShdr = true;
    options.parseFont = true;
    options.parseTmln = true;
    options.parseObjt = true;
    options.parseRoom = true;
    options.parseTpag = true;
    options.parseCode = true;
    options.parseVari = true;
    options.parseFunc = true;
    options.parseStrg = true;
    options.parseTxtr = false;
    options.parseAudo = false;
    options.skipLoadingPreciseMasksForNonPreciseSprites = true;
    options.lazyLoadRooms = lazyLoadRooms;
    options.eagerlyLoadedRooms = eagerRooms;
    options.progressCallback = PS2Overlay_statusScreenCallback;
    options.progressCallbackUserData = PS2Overlay_getCallbackData();
    
    DataWin* dataWin = DataWin_parse(dataWinPath, options);
    free(dataWinPath);
    shfree(eagerRooms);

    bool wadVersionSupported = false;
#ifdef ENABLE_WAD14
    if (14 >= dataWin->gen8.wadVersion) wadVersionSupported = true;
#endif
#ifdef ENABLE_WAD16
    if (dataWin->gen8.wadVersion == 15 || dataWin->gen8.wadVersion == 16) wadVersionSupported = true;
#endif
#ifdef ENABLE_WAD17
    if (dataWin->gen8.wadVersion == 17) wadVersionSupported = true;
#endif

    if (!wadVersionSupported) {
        char errorText[128];
        snprintf(errorText, sizeof(errorText), "Unsupported WAD version %u!", dataWin->gen8.wadVersion);
        PS2Overlay_drawStatusScreen(dataWin->gen8.displayName, errorText, true);
        while (true) {}
    }

    {
        void* heapTop = sbrk(0);
        int32_t usedBytes = (int32_t) (uintptr_t) heapTop;
        int32_t freeBytes = MAX_MEMORY_BYTES - usedBytes;
        printf("Memory after data.win parsing: used=%d bytes (%.1f KB), total=%d bytes (%.1f KB), free=%d bytes (%.1f KB)\n", usedBytes, (double) (usedBytes / 1024.0f), MAX_MEMORY_BYTES, (double) (MAX_MEMORY_BYTES / 1024.0f), freeBytes, (double) (freeBytes / 1024.0f));
    }

    FileSystem* fileSystem = Ps2FileSystem_create(configRoot, dataWin->gen8.displayName);
    if (fileSystem == nullptr) {
        PS2Overlay_drawStatusScreen(dataWin->gen8.displayName, "CONFIG.JSN is missing the fileSystem configuration!", true);
        while (true) {}
    }

    PS2Overlay_drawStatusScreen(dataWin->gen8.displayName, "Creating VM...", true);

    VMContext* vm = VM_create(dataWin);

    // ===[ Initialize Renderer ]===
    PS2Overlay_drawStatusScreen(dataWin->gen8.displayName, "Initializing renderer...", true);

    int64_t eeAtlasCacheBytes = JsonReader_getInt(JsonReader_getJsonValueByKey(configRoot, "eeAtlasCacheBytes"));
    Renderer* renderer = GsRenderer_create(gsGlobal, eeAtlasCacheBytes);

    // ===[ Initialize Audio System ]===
#ifdef USE_PS2_AUDIO
    PS2Overlay_drawStatusScreen(dataWin->gen8.displayName, "Initializing audio...", true);
    Ps2AudioSystem* ps2Audio = Ps2AudioSystem_create();
    AudioSystem* audioSystem = (AudioSystem*) ps2Audio;
#else
    AudioSystem* audioSystem = (AudioSystem*) NoopAudioSystem_create();
#endif

    PS2Overlay_drawStatusScreen(dataWin->gen8.displayName, "Creating runner...", true);
    Runner* runner = Runner_create(dataWin, vm, renderer, fileSystem, audioSystem);

    // Parse disabledObjects from CONFIG.JSN
    JsonValue* disabledObjectsArr = JsonReader_getJsonValueByKey(configRoot, "disabledObjects");
    if (disabledObjectsArr != nullptr && JsonReader_isArray(disabledObjectsArr)) {
        sh_new_strdup(runner->disabledObjects);
        int disabledCount = JsonReader_arrayLength(disabledObjectsArr);
        repeat(disabledCount, i) {
            JsonValue* elem = JsonReader_getArrayElement(disabledObjectsArr, i);
            if (elem != nullptr && JsonReader_isString(elem)) {
                const char* objName = JsonReader_getString(elem);
                shput(runner->disabledObjects, objName, 1);
                printf("Disabled object: %s\n", objName);
            }
        }
    }

    // Parse pad mappings from CONFIG.JSN (one object per controller, both optional)
    parsePadMappings(configRoot, "controller1Mappings", &pad1Mappings, &pad1MappingCount, "controller1");
    parsePadMappings(configRoot, "controller2Mappings", &pad2Mappings, &pad2MappingCount, "controller2");

    JsonValue* gamepadObj = JsonReader_getJsonValueByKey(configRoot, "gamepad");
    if (gamepadObj != nullptr && JsonReader_isObject(gamepadObj)) {
        gamepadApiEnabled = JsonReader_getBool(JsonReader_getJsonValueByKey(gamepadObj, "enabled"));
    }
    if (gamepadApiEnabled) {
        printf("CONFIG.JSN: GameMaker gamepad API enabled\n");
    }

    {
        void* heapTop = sbrk(0);
        int32_t usedBytes = (int32_t) (uintptr_t) heapTop;
        int32_t freeBytes = MAX_MEMORY_BYTES - usedBytes;
        printf("Memory after VM and runner creation: used=%d bytes (%.1f KB), total=%d bytes (%.1f KB), free=%d bytes (%.1f KB)\n", usedBytes, (double) (usedBytes / 1024.0f), MAX_MEMORY_BYTES, (double) (MAX_MEMORY_BYTES / 1024.0f), freeBytes, (double) (freeBytes / 1024.0f));
    }

    PS2Overlay_drawStatusScreen(dataWin->gen8.displayName, "Initializing first room...", true);
    Runner_initFirstRoom(runner);

    PS2Overlay_drawStatusScreen(dataWin->gen8.displayName, "Reticulating splines...", true);

    // ===[ gprof Profiler Setup ]===
#ifdef GPROF_PROFILING
    // Reset profiler to ignore any data collected during the initialization steps
    gprof_stop(nullptr, 0);

    // If not running from host:, load USB mass storage drivers so we can write gmon.out to mass:
    if (strcmp(deviceKey.key, "host") != 0)
        PS2Utils_loadMassStorageDrivers();

    gprof_start();
    fprintf(stderr, "gprof: Profiling started!\n");
#endif

    Gen8* gen8 = &dataWin->gen8;
    int32_t gameW = (int32_t) gen8->defaultWindowWidth;
    int32_t gameH = (int32_t) gen8->defaultWindowHeight;

    // ===[ Initialize Timer ]===
    InitTimer(kBUSCLK);
    StartTimerSystemTime();

    // ===[ Main Loop ]===
    bool debugOverlayStartEnabled = JsonReader_getBool(JsonReader_getJsonValueByKey(configRoot, "debugOverlayEnabled"));
    PS2Overlay_setDebugOverlayState(debugOverlayStartEnabled ? STATS_ENABLED : STATS_DISABLED, runner);

    u64 lastFrameStartTime = GetTimerSystemTime(); // for delta_time
    while (!runner->shouldExit) {
        u64 frameStartTime = GetTimerSystemTime();
        u64 deltaTicks = frameStartTime - lastFrameStartTime;
        runner->deltaTime = (double) (deltaTicks * 1000000ULL / (u64) kBUSCLK);
        lastFrameStartTime = frameStartTime;

        // ===[ Poll Controller (always poll every vsync) ]===
        // NOTE: We do NOT call RunnerKeyboard_beginFrame here! Pressed/released edges accumulate across vsyncs so that quick taps on non-game-frame
        // vsyncs are not lost
        //
        // beginFrame is called after the game consumes input.

        if (padOpened[0]) pollPad(runner, 0, pad1Mappings, pad1MappingCount, &prevButtons[0], &padWasStable[0]);
        if (padOpened[1]) pollPad(runner, 1, pad2Mappings, pad2MappingCount, &prevButtons[1], &padWasStable[1]);

        if (gamepadApiEnabled) {
            RunnerGamepad_beginFrame(runner->gamepads);
            if (padOpened[0]) Ps2Gamepad_poll(runner->gamepads, 0);
            if (padOpened[1]) Ps2Gamepad_poll(runner->gamepads, 1);
        }

        // ===[ Poll USB Keyboard ]===
        // Drain all pending RAW events this vsync so press/release edges aren't dropped.
        if (kbdAvailable) {
            PS2KbdRawKey rawKey;
            while (PS2KbdReadRaw(&rawKey) > 0) {
                int32_t gmlKey = hidUsageToGmlKey(rawKey.key);

                // Track shift modifier locally so we can pick the correct glyph for onCharacter.
                if (rawKey.key == 0xE1 || rawKey.key == 0xE5) {
                    kbdShiftHeld = (rawKey.state == PS2KBD_RAWKEY_DOWN);
                }

                if (rawKey.state == PS2KBD_RAWKEY_DOWN) {
                    if (gmlKey >= 0) RunnerKeyboard_onKeyDown(runner->keyboard, gmlKey);
                    unsigned int ch = hidUsageToAsciiChar(rawKey.key, kbdShiftHeld);
                    if (ch != 0) RunnerKeyboard_onCharacter(runner->keyboard, ch);
                } else if (rawKey.state == PS2KBD_RAWKEY_UP) {
                    if (gmlKey >= 0) RunnerKeyboard_onKeyUp(runner->keyboard, gmlKey);
                }
            }
        }

        // R2 on pad1 removes speed cap (ignore waiting for vsync)
        bool speedCapRemoved = padWasStable[0] && ((prevButtons[0] & PAD_R2) == 0);

        // Go to next room
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_PAGEUP)) {
            DataWin* dw = runner->dataWin;
            if ((int32_t) dw->gen8.roomOrderCount > runner->currentRoomOrderPosition + 1) {
                int32_t nextIdx = dw->gen8.roomOrder[runner->currentRoomOrderPosition + 1];
                runner->pendingRoom = nextIdx;
                runner->audioSystem->vtable->stopAll(runner->audioSystem);
                fprintf(stderr, "Debug: Going to next room -> %s\n", dw->room.rooms[nextIdx].name);
            }
        }

        // Go to previous room
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_PAGEDOWN)) {
            DataWin* dw = runner->dataWin;
            forEachIndexed(Room, room, i, dw->room.rooms, dw->room.count) {
                if (strcmp(room->name, "room_asrielappears") == 0) {
                    runner->pendingRoom = i;
                    runner->audioSystem->vtable->stopAll(runner->audioSystem);
                    break;
                }
            }
        }

        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_F12)) {
            PS2Overlay_toggleDebugOverlay(runner);
        }

        // Reset global interact state because I HATE when I get stuck while moving through rooms
        if (RunnerKeyboard_checkPressed(runner->keyboard, VK_F10)) {
            int32_t interactVarId = shget(runner->vmContext->varNameMap, "interact");

            Instance_setSelfVar(runner->vmContext->globalScopeInstance, interactVarId, RValue_makeInt32(0));
            printf("Changed global.interact [%d] value!\n", interactVarId);
        }

        // ===[ Game Logic ]===
        uint32_t roomSpeed = runner->currentRoom->speed;

        u64 stepStartTime = GetTimerSystemTime();
        Runner_step(runner);
        u64 stepEndTime = GetTimerSystemTime();

        gsKit_clear(gsGlobal, GS_SETREG_RGBAQ(0x00, 0x00, 0x00, 0x80, 0x00));

        Runner_drawPre(runner, 640, 448);
        Runner_beginFrame(runner, gameW, gameH, 640, 448, 640, 448);

        // Render views
        u64 drawStartTime = GetTimerSystemTime();
        Runner_drawViews(runner, gameW, gameH, false);
        runner->viewCurrent = 0;
        renderer->vtable->endFrameInit(renderer);
        Runner_drawPost(runner, 640, 448);
        renderer->vtable->endFrameEnd(renderer);
        Runner_drawGUI(runner, 640, 448, gameW, gameH);
        u64 drawEndTime = GetTimerSystemTime();

        // Clear pressed/released edges after both Step and Draw have consumed input
        // This MUST be after Runner_draw because games CAN handle input in Draw events (e.g. Undertale's naming screen)
        RunnerKeyboard_beginFrame(runner->keyboard);

        u64 audioStartTime = GetTimerSystemTime();
        // Update audio system (gain fading, stream to audsrv)
        float dt = 1.0f / (float) roomSpeed;
        if (0.0f > dt) dt = 0.0f;
        if (dt > 0.1f) dt = 0.1f;
        runner->audioSystem->vtable->update(runner->audioSystem, dt);
        u64 audioEndTime = GetTimerSystemTime();

        u64 runnerEndTime = GetTimerSystemTime();
        u64 duration = runnerEndTime - frameStartTime;
        u64 stepDuration = stepEndTime - stepStartTime;
        u64 drawDuration = drawEndTime - drawStartTime;
        u64 audioDuration = audioEndTime - audioStartTime;
        float tickTime = (float) duration / (float) (kBUSCLK / 1000);
        float stepTime = (float) stepDuration / (float) (kBUSCLK / 1000);
        float drawTime = (float) drawDuration / (float) (kBUSCLK / 1000);
        float audioTime = (float) audioDuration / (float) (kBUSCLK / 1000);

        // ===[ Debug Overlay ]===
        PS2Overlay_drawDebugOverlay(renderer, runner, tickTime, stepTime, drawTime, audioTime, speedCapRemoved);

        // Execute draw queue and flip buffers.
        // Only swap when there isn't a room change to match the original runner.
        gsKit_queue_exec(gsGlobal);
        if (runner->pendingRoom == -1) {
            gsKit_sync_flip(gsGlobal);
        }
        Runner_handlePendingRoomChange(runner);

        // Busy-wait until enough time has elapsed for this frame if needed
        if (!speedCapRemoved && roomSpeed > 0) {
            u64 targetTicks = kBUSCLK / roomSpeed;
            while (targetTicks > GetTimerSystemTime() - frameStartTime) {
                // spin spin spin!
            }
        }
    }

    // ===[ gprof Profiler Output ]===
#ifdef GPROF_PROFILING
    {
        const char* gprofPath;
        if (strcmp(deviceKey.key, "host") == 0) {
            gprofPath = "host:gmon.out";
        } else {
            gprofPath = "mass:gmon.out";
        }
        fprintf(stderr, "gprof: Writing profiling data to %s\n", gprofPath);
        gprof_stop(gprofPath, 1);
        fprintf(stderr, "gprof: Done\n");
    }
#endif

    // For some god awful reason PCSX2 crashes when destroying the audio system (???)
    // runner->audioSystem->vtable->destroy(runner->audioSystem);
    runner->audioSystem = nullptr;
    renderer->vtable->destroy(renderer);
    DataWin_free(dataWin);
    PS2Overlay_deinit();

    return 0;
}
